### ISSUE TITLE
yolov5 package version

### ISSUE THREAD

**Issue by fcakyon** [da-tubi/rikai-example#2]
Thanks a lot for this awesome repo!

**v6.0.6** release of yolov5 is out: https://pypi.org/project/yolov5/6.0.6/

Feel free to update your yolov5 version in [requirements.txt](https://github.com/da-tubi/rikai-example/blob/main/requirements.txt#L132) file!

**Comment by da-tubi** [comment]
See https://github.com/eto-ai/rikai/blob/master/contrib/yolov5/REAMDE.md
and https://pypi.org/project/rikai-yolov5/

Now (https://github.com/eto-ai/rikai/pull/391) using yolov5 in Rikai-enhanced Spark SQL is as simple as:

``` sql
CREATE MODEL yolov5
FLAVOR yolov5
PREPROCESSOR 'rikai.contrib.yolov5.transforms.pre_processing'
POSTPROCESSOR 'rikai.contrib.yolov5.transforms.post_processing'
OPTIONS (device="cpu", batch_size=32)
RETURNS {OUTPUT_SCHEMA}
USING "torchhub:///ultralytics/yolov5:v6.0/yolov5s";

select ML_PREDICT(yolov5, "path/to/lena.png")
```
